# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06da28c7a46fd48e060e77378f4aa44dfbd4e950f1cdd9c5170b3bbca874f940b746a3fe54ac26f702ff4233377d0a28a28841f63e6140aff7b66941e1b27c9

test:
  secret_key_base: 604988190716da340d63a2556a3e6f239d055589d5513ed3ae77a5b3d3a595690168e15fc194e857d296f84b3bb0ae1fb40c6a803a3e0a801b9e67022da1ff03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
